- project:
    name: openstack/zaqar
    check:
      jobs:
        # TripleO jobs that deploy Zaqar.
        # Note we don't use a project-template here, so it's easier
        # to disable voting on one specific job if things go wrong.
        # tripleo-ci-centos-7-scenario002-multinode-oooq will only
        # run on stable/pike while the -container will run in Queens
        # and beyond.
        # If you need any support to debug these jobs in case of
        # failures, please reach us on #tripleo IRC channel.
        - tripleo-ci-centos-7-scenario002-multinode-oooq
        - tripleo-ci-centos-7-scenario002-multinode-oooq-container
    gate:
      jobs:
        - tripleo-ci-centos-7-scenario002-multinode-oooq
        - tripleo-ci-centos-7-scenario002-multinode-oooq-container
