- hosts: all
  roles:
    - run-devstack
    # Run bindep after devstack so that they won't interfere
    - role: bindep
      bindep_profile: test
      bindep_dir: "{{ zuul_work_dir }}"
    - ensure-tox
    - get-devstack-os-environment
    - tox

